language: python

python:
  - "2.7"

# Use container-based infrastructure
sudo: false

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -y update
  - sudo apt-get -y install build-essential
  - sudo apt-get -y install g++-5
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 1
  - g++ --version
  - pip install Cython==0.27.2

install:
  - pip install .
  - pip install -r requirements.txt


script:
  - python whatthelang/test_predict_lang.py


deploy:
  provider: pypi
  user: "indix"
  password:
    secure: "RpG4xzViswPyfZa8Yz8fwIqQGSch+Z6QqjrwzfJJGPyCfgjq3IN7BKEJdl+CWrtK6ALjx8HFuP+n9LdCrUge8r1Bqc5ck2HcaY1d1rmsO/pkqTp9bKxymdg1piBGazCb0g0hkN74JT2/kXyP+w13VAKaxpYRbG"